# imported from KiCad Fuse:Fuse_Littelfuse-NANO2-451_453
name = "Fuse_Littelfuse-NANO2-451_453"
description = "Littelfuse NANO2 https://www.littelfuse.com/~/media/electronics/datasheets/fuses/littelfuse_fuse_451_453_datasheet.pdf.pdf"
tags = ["Fuse", "Nano2"]
mount = "smd"
height = "2.4mm"

[[pads]]
number = "1"
kind = "smd"
shape = "rect"
at = [-2.455, 0.0]
size = [1.96, 3.15]
layers = ["F.Cu", "F.Mask", "F.Paste"]

[[pads]]
number = "2"
kind = "smd"
shape = "rect"
at = [2.455, 0.0]
size = [1.96, 3.15]
layers = ["F.Cu", "F.Mask", "F.Paste"]

[[graphics]]
kind = "text"
layer = "F.SilkS"
at = [0.0, -2.5]
text = "${REFERENCE}"
size = 1.0

[[graphics]]
kind = "text"
layer = "F.Fab"
at = [0.0, 2.7]
text = "${VALUE}"
size = 1.0

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-1.215, -1.455]
end = [1.215, -1.455]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-1.215, 1.455]
end = [1.215, 1.455]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [-3.69, -1.83]
end = [3.69, -1.83]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [-3.69, 1.83]
end = [-3.69, -1.83]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [3.69, -1.83]
end = [3.69, 1.83]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [3.69, 1.83]
end = [-3.69, 1.83]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-3.05, -1.345]
end = [-3.05, 1.345]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-3.05, -1.345]
end = [3.05, -1.345]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-3.05, 1.345]
end = [3.05, 1.345]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [3.05, 1.345]
end = [3.05, -1.345]
width = 0.1

[[graphics]]
kind = "text"
layer = "F.Fab"
at = [0.0, 0.0]
text = "${REFERENCE}"
size = 1.0
