name = "buggy-guard"
board = "buggy-guard"
schematic = "buggy-guard"

[[footprints]]
ref = "H1"
at = [4.0, 4.0]
locked = true
label = { at = [4.0, 8.43] }

[[footprints]]
ref = "H2"
at = [96.0, 4.0]
locked = true
label = { at = [96.0, 8.43] }

[[footprints]]
ref = "H3"
at = [4.0, 76.0]
locked = true

[[footprints]]
ref = "H4"
at = [96.0, 76.0]
locked = true

[[footprints]]
ref = "J1"
at = [6.5, 12.0]
rotation = 270.0
locked = true

[[footprints]]
ref = "J4"
at = [6.5, 48.0]
rotation = 270.0
locked = true
label = { at = [6.81, 43.99] }

[[footprints]]
ref = "J7"
at = [11.0, 75.0]
locked = true

[[footprints]]
ref = "J5"
at = [22.0, 75.0]
locked = true
label = { at = [17.84, 71.18] }

[[footprints]]
ref = "J6"
at = [31.0, 75.0]
locked = true

[[footprints]]
ref = "J12"
at = [42.0, 75.0]
locked = true
label = { at = [37.36, 71.18] }

[[footprints]]
ref = "J13"
at = [53.0, 75.0]
locked = true
label = { at = [62.64, 75.53] }

[[footprints]]
ref = "J8"
at = [95.0, 20.0]
rotation = 90.0
locked = true
label = { at = [93.78, 8.58] }

[[footprints]]
ref = "J9"
at = [95.0, 34.5]
rotation = 90.0
locked = true
label = { at = [90.96, 38.43] }

[[footprints]]
ref = "J10"
at = [95.0, 49.0]
rotation = 90.0
locked = true

[[footprints]]
ref = "J11"
at = [95.0, 63.5]
rotation = 90.0
locked = true
label = { at = [95.53, 67.43] }

[[footprints]]
ref = "J2"
at = [62.0, 4.2]
rotation = 180.0
locked = true
label = { at = [68.53, 3.26] }

[[footprints]]
ref = "J3"
at = [45.0, 4.0]
rotation = 180.0
locked = true

[[footprints]]
ref = "U3"
at = [78.0, 20.0]
locked = true
label = { at = [66.94, 9.18] }

[[footprints]]
ref = "F1"
at = [16.0, 7.0]
locked = true

[[footprints]]
ref = "D1"
at = [24.0, 7.0]
rotation = 180.0
locked = true

[[footprints]]
ref = "D2"
at = [30.5, 11.0]
rotation = 270.0
locked = true
label = { at = [30.5, 6.53] }

[[footprints]]
ref = "C1"
at = [19.0, 20.0]
locked = true

[[footprints]]
ref = "C3"
at = [27.5, 18.0]
rotation = 270.0
locked = true
label = { at = [27.0, 14.73] }

[[footprints]]
ref = "C2"
at = [31.0, 18.0]
rotation = 270.0
locked = true
label = { at = [30.0, 21.28] }

[[footprints]]
ref = "U1"
at = [37.0, 17.0]
locked = true
label = { at = [41.87, 15.75] }

[[footprints]]
ref = "C4"
at = [42.0, 13.5]
rotation = 90.0
locked = true

[[footprints]]
ref = "L1"
at = [50.5, 17.0]
locked = true

[[footprints]]
ref = "C7"
at = [59.5, 16.0]
rotation = 270.0
locked = true
label = { at = [57.38, 16.0], rotation = 90.0 }

[[footprints]]
ref = "C8"
at = [62.5, 16.0]
rotation = 270.0
locked = true
label = { at = [63.75, 11.73] }

[[footprints]]
ref = "U4"
at = [61.0, 11.3]
locked = true
label = { at = [57.98, 11.3], rotation = 90.0 }

[[footprints]]
ref = "D3"
at = [66.0, 20.0]
rotation = 90.0
locked = true
label = { at = [62.97, 20.0] }

[[footprints]]
ref = "U2"
at = [62.0, 24.0]
locked = true
label = { at = [57.94, 27.38] }

[[footprints]]
ref = "Q3"
at = [20.0, 53.0]
locked = true

[[footprints]]
ref = "D9"
at = [21.0, 60.0]
locked = true
label = { at = [25.76, 60.0] }

[[footprints]]
ref = "Q2"
at = [27.0, 47.0]
locked = true
label = { at = [27.0, 49.68] }

[[footprints]]
ref = "U9"
at = [26.0, 66.0]
locked = true
label = { at = [26.0, 62.33] }

[[footprints]]
ref = "U5"
at = [40.0, 44.0]
locked = true
label = { at = [43.46, 44.0] }

[[footprints]]
ref = "U6"
at = [50.0, 40.0]
locked = true
label = { at = [50.0, 37.53] }

[[footprints]]
ref = "U7"
at = [46.0, 50.0]
locked = true
label = { at = [46.0, 52.68] }

[[footprints]]
ref = "U8"
at = [53.0, 50.0]
locked = true
label = { at = [49.64, 50.0] }

[[footprints]]
ref = "BZ1"
at = [70.0, 60.0]
locked = true

[[footprints]]
ref = "SW1"
at = [62.0, 36.0]
locked = true
label = { at = [62.0, 39.98] }

[[footprints]]
ref = "SW2"
at = [72.0, 36.0]
locked = true

[[footprints]]
ref = "R1"
at = [36.9, 12.05]
rotation = 180.0
label = { at = [36.9, 13.48] }

[[footprints]]
ref = "R2"
at = [35.25, 20.45]
rotation = 180.0
label = { at = [35.25, 21.88] }

[[footprints]]
ref = "R3"
at = [32.2, 21.05]
rotation = 180.0
label = { at = [32.95, 22.76] }

[[footprints]]
ref = "R4"
at = [41.15, 20.2]
rotation = 180.0
label = { at = [41.15, 21.63] }

[[footprints]]
ref = "R5"
at = [38.5, 21.95]
label = { at = [38.5, 20.52] }

[[footprints]]
ref = "R6"
at = [34.65, 25.65]
rotation = 90.0
label = { at = [33.22, 25.65], rotation = 90.0 }

[[footprints]]
ref = "C5"
at = [30.95, 24.9]
rotation = 180.0
label = { at = [30.95, 26.33] }

[[footprints]]
ref = "C6"
at = [36.9, 24.9]
label = { at = [36.9, 23.47] }

[[footprints]]
ref = "C9"
at = [58.45, 24.35]
rotation = 180.0
label = { at = [58.45, 25.78] }

[[footprints]]
ref = "C10"
at = [60.2, 27.3]
rotation = 180.0
label = { at = [60.2, 29.01] }

[[footprints]]
ref = "R7"
at = [34.3, 13.55]
label = { at = [34.3, 12.12] }

[[footprints]]
ref = "R8"
at = [89.25, 11.2]
label = { at = [89.25, 9.77] }

[[footprints]]
ref = "C11"
at = [89.25, 14.15]
label = { at = [89.25, 12.72] }

[[footprints]]
ref = "R9"
at = [62.75, 21.5]
label = { at = [59.31, 22.75] }

[[footprints]]
ref = "D4"
at = [65.3, 70.55]
rotation = 90.0
label = { at = [63.62, 70.55], rotation = 90.0 }

[[footprints]]
ref = "C12"
at = [70.95, 6.4]
label = { at = [70.95, 4.97] }

[[footprints]]
ref = "C13"
at = [66.65, 12.95]
rotation = 180.0
label = { at = [66.65, 14.38] }

[[footprints]]
ref = "R10"
at = [66.65, 25.8]
label = { at = [66.65, 24.37] }

[[footprints]]
ref = "C14"
at = [63.4, 26.6]
rotation = 180.0
label = { at = [63.4, 28.03] }

[[footprints]]
ref = "R11"
at = [81.05, 31.05]
rotation = 180.0
label = { at = [81.05, 32.48] }

[[footprints]]
ref = "R12"
at = [55.95, 4.7]
rotation = 90.0
label = { at = [54.52, 4.7], rotation = 90.0 }

[[footprints]]
ref = "R13"
at = [55.95, 7.85]
rotation = 90.0
label = { at = [54.52, 7.85], rotation = 90.0 }

[[footprints]]
ref = "R14"
at = [83.9, 4.95]
rotation = 180.0
label = { at = [83.9, 6.38] }

[[footprints]]
ref = "D5"
at = [80.8, 6.1]
label = { at = [80.8, 4.42] }

[[footprints]]
ref = "R15"
at = [88.6, 5.3]
label = { at = [88.6, 3.87] }

[[footprints]]
ref = "R16"
at = [89.5, 19.45]
rotation = 270.0
label = { at = [90.93, 19.45], rotation = 90.0 }

[[footprints]]
ref = "Q1"
at = [89.75, 22.75]
rotation = 180.0
label = { at = [89.75, 25.5] }

[[footprints]]
ref = "D6"
at = [57.55, 49.55]
label = { at = [57.55, 47.55] }

[[footprints]]
ref = "C15"
at = [39.7, 41.05]
label = { at = [39.7, 39.62] }

[[footprints]]
ref = "R17"
at = [36.25, 43.5]
label = { at = [36.25, 42.07] }

[[footprints]]
ref = "R18"
at = [70.7, 46.3]
label = { at = [70.7, 44.87] }

[[footprints]]
ref = "C16"
at = [48.65, 42.25]
rotation = 180.0
label = { at = [48.65, 43.68] }

[[footprints]]
ref = "C17"
at = [53.35, 40.75]
label = { at = [53.35, 39.32] }

[[footprints]]
ref = "R19"
at = [47.45, 39.9]
rotation = 90.0
label = { at = [46.02, 39.9], rotation = 90.0 }

[[footprints]]
ref = "R20"
at = [51.0, 34.8]
label = { at = [51.0, 33.37] }

[[footprints]]
ref = "R21"
at = [43.8, 32.25]
rotation = 90.0
label = { at = [42.37, 32.25], rotation = 90.0 }

[[footprints]]
ref = "C18"
at = [47.65, 47.55]
label = { at = [47.65, 46.12] }

[[footprints]]
ref = "R22"
at = [62.1, 45.15]
rotation = 90.0
label = { at = [60.67, 45.15], rotation = 90.0 }

[[footprints]]
ref = "C19"
at = [54.9, 47.55]
label = { at = [54.9, 46.12] }

[[footprints]]
ref = "R23"
at = [74.05, 42.5]
rotation = 270.0
label = { at = [75.48, 42.5], rotation = 90.0 }

[[footprints]]
ref = "R24"
at = [34.45, 50.95]
label = { at = [34.45, 49.52] }

[[footprints]]
ref = "R26"
at = [25.3, 44.0]
rotation = 90.0
label = { at = [23.87, 44.0], rotation = 90.0 }

[[footprints]]
ref = "D7"
at = [25.3, 40.85]
rotation = 270.0
label = { at = [26.98, 40.85], rotation = 90.0 }

[[footprints]]
ref = "R27"
at = [29.4, 45.7]
label = { at = [29.4, 44.27] }

[[footprints]]
ref = "R28"
at = [14.1, 57.25]
rotation = 180.0
label = { at = [14.1, 58.68] }

[[footprints]]
ref = "D8"
at = [16.3, 48.35]
label = { at = [16.3, 46.35] }

[[footprints]]
ref = "R29"
at = [26.25, 53.25]
label = { at = [26.25, 51.82] }

[[footprints]]
ref = "R30"
at = [74.4, 9.25]
label = { at = [74.4, 7.82] }

[[footprints]]
ref = "R31"
at = [77.45, 9.4]
label = { at = [77.45, 7.97] }

[[footprints]]
ref = "C20"
at = [71.2, 9.4]
label = { at = [71.2, 7.97] }

[[footprints]]
ref = "Q4"
at = [40.55, 67.7]
rotation = 270.0
label = { at = [43.3, 67.7], rotation = 90.0 }

[[footprints]]
ref = "Q5"
at = [42.45, 60.15]
rotation = 90.0
label = { at = [39.7, 60.15], rotation = 90.0 }

[[footprints]]
ref = "F2"
at = [32.05, 68.8]
label = { at = [32.05, 66.97] }

[[footprints]]
ref = "R32"
at = [56.9, 58.9]
rotation = 90.0
label = { at = [55.47, 58.9], rotation = 90.0 }

[[footprints]]
ref = "R33"
at = [79.95, 37.0]
rotation = 180.0
label = { at = [79.95, 38.43] }

[[footprints]]
ref = "C21"
at = [89.25, 15.65]
rotation = 180.0
label = { at = [89.25, 17.08] }

[[footprints]]
ref = "R34"
at = [63.6, 29.55]
rotation = 180.0
label = { at = [63.6, 30.98] }

[[footprints]]
ref = "C22"
at = [52.1, 60.35]
rotation = 180.0
label = { at = [52.1, 61.78] }

[[footprints]]
ref = "R35"
at = [33.35, 61.0]
rotation = 180.0
label = { at = [33.35, 62.43] }

[[footprints]]
ref = "C23"
at = [26.5, 69.45]
rotation = 180.0
label = { at = [26.5, 70.88] }

[[footprints]]
ref = "C24"
at = [31.35, 65.45]
label = { at = [31.35, 64.02] }

[[footprints]]
ref = "R36"
at = [22.25, 69.2]
rotation = 180.0
label = { at = [22.25, 70.63] }

[[footprints]]
ref = "R37"
at = [20.7, 65.95]
rotation = 180.0
label = { at = [20.7, 67.38] }

[[footprints]]
ref = "R38"
at = [20.4, 63.35]
rotation = 90.0
label = { at = [18.97, 63.35], rotation = 90.0 }

[[footprints]]
ref = "C25"
at = [46.85, 59.9]
rotation = 270.0
label = { at = [48.28, 59.9], rotation = 90.0 }

[[footprints]]
ref = "R39"
at = [51.4, 55.95]
rotation = 90.0
label = { at = [49.97, 55.95], rotation = 90.0 }

[[footprints]]
ref = "R40"
at = [59.65, 19.55]
rotation = 180.0
label = { at = [59.65, 20.98] }

[[footprints]]
ref = "F3"
at = [29.45, 62.1]
label = { at = [29.45, 60.27] }

[[footprints]]
ref = "C27"
at = [51.85, 28.15]
rotation = 270.0
label = { at = [53.28, 28.15], rotation = 90.0 }

[[footprints]]
ref = "R41"
at = [85.0, 9.4]
label = { at = [85.0, 7.97] }

[[footprints]]
ref = "R42"
at = [88.05, 8.25]
label = { at = [88.05, 6.82] }

[[footprints]]
ref = "R43"
at = [80.5, 9.4]
label = { at = [80.5, 7.97] }

[[footprints]]
ref = "R44"
at = [89.85, 32.0]
label = { at = [89.85, 30.57] }

[[footprints]]
ref = "R45"
at = [89.5, 28.2]
rotation = 270.0
label = { at = [90.93, 28.2], rotation = 90.0 }

[[footprints]]
ref = "R46"
at = [66.65, 27.3]
rotation = 180.0
label = { at = [66.65, 28.73] }

[[footprints]]
ref = "R47"
at = [88.65, 46.45]
label = { at = [88.65, 45.02] }

[[footprints]]
ref = "R48"
at = [88.65, 37.8]
rotation = 270.0
label = { at = [86.16, 37.8] }

[[footprints]]
ref = "R49"
at = [85.9, 34.0]
rotation = 180.0
label = { at = [85.9, 35.43] }

[[footprints]]
ref = "R50"
at = [89.25, 59.5]
rotation = 270.0
label = { at = [89.25, 57.05] }

[[footprints]]
ref = "R51"
at = [88.95, 52.4]
rotation = 270.0
label = { at = [90.38, 52.4], rotation = 90.0 }

[[footprints]]
ref = "R52"
at = [85.95, 31.05]
rotation = 180.0
label = { at = [85.95, 32.48] }

[[footprints]]
ref = "R53"
at = [46.7, 71.15]
label = { at = [46.7, 69.72] }

[[footprints]]
ref = "R54"
at = [58.85, 61.95]
rotation = 180.0
label = { at = [58.85, 63.38] }

[[footprints]]
ref = "R55"
at = [77.85, 35.5]
label = { at = [77.85, 34.07] }

[[footprints]]
ref = "C26"
at = [77.9, 32.55]
label = { at = [77.9, 31.12] }

[[footprints]]
ref = "R56"
at = [61.65, 48.9]
rotation = 180.0
label = { at = [61.65, 50.33] }

[[footprints]]
ref = "R57"
at = [66.75, 30.35]
rotation = 180.0
label = { at = [69.21, 31.6], rotation = 90.0 }

[[footprints]]
ref = "R58"
at = [62.4, 61.75]
rotation = 270.0
label = { at = [63.83, 61.75], rotation = 90.0 }

[[footprints]]
ref = "R59"
at = [80.95, 34.0]
rotation = 180.0
label = { at = [80.95, 35.43] }
