# imported from KiCad Device:Fuse
name = "Fuse"
reference = "F"
description = "Fuse"
keywords = ["fuse"]
footprint = "Fuse_Littelfuse-NANO2-451_453"
footprint_filters = ["*Fuse*"]
pin_names = "outside"
hide_pin_numbers = true

[[graphics]]
kind = "rect"
start = [-0.762, 2.54]
end = [0.762, -2.54]
width = 0.254

[[graphics]]
kind = "polyline"
points = [[0.0, -2.54], [0.0, 2.54]]

[[pins]]
number = "1"
type = "passive"
at = [0.0, -3.81]
side = "top"
length = 1.27
unit = 1

[[pins]]
number = "2"
type = "passive"
at = [0.0, 3.81]
side = "bottom"
length = 1.27
unit = 1
