# imported from KiCad Device:R
name = "R"
reference = "R"
description = "Resistor"
keywords = ["R", "res", "resistor"]
footprint = "R_0603_1608Metric"
footprint_filters = ["R_*"]
pin_names = "outside"
hide_pin_numbers = true

[[graphics]]
kind = "rect"
start = [-1.016, 2.54]
end = [1.016, -2.54]
width = 0.254

[[pins]]
number = "1"
type = "passive"
at = [0.0, -3.81]
side = "top"
length = 1.27
unit = 1

[[pins]]
number = "2"
type = "passive"
at = [0.0, 3.81]
side = "bottom"
length = 1.27
unit = 1
