# imported from KiCad Diode:SS14
name = "SS14"
reference = "D"
description = "40V 1A Schottky Diode, SMA"
datasheet = "https://www.vishay.com/docs/88746/ss12.pdf"
keywords = ["diode", "Schottky"]
footprint = "Diode_SMD:D_SMA"
footprint_filters = ["D*SMA*"]
pin_names = "hidden"
pin_name_offset = 1.016
hide_pin_numbers = true

[[graphics]]
kind = "polyline"
points = [[-1.905, -0.635], [-1.905, -1.27], [-1.27, -1.27], [-1.27, 1.27], [-0.635, 1.27], [-0.635, 0.635]]
width = 0.254

[[graphics]]
kind = "polygon"
points = [[1.27, -1.27], [1.27, 1.27], [-1.27, 0.0]]
width = 0.254

[[graphics]]
kind = "polyline"
points = [[1.27, 0.0], [-1.27, 0.0]]

[[pins]]
number = "1"
name = "K"
type = "passive"
at = [-3.81, 0.0]
side = "left"
length = 2.54
unit = 1

[[pins]]
number = "2"
name = "A"
type = "passive"
at = [3.81, 0.0]
side = "right"
length = 2.54
unit = 1
