# imported from KiCad Power_Protection:USBLC6-2SC6
name = "USBLC6-2SC6"
reference = "U"
description = "Very low capacitance ESD protection diode, 2 data-line, SOT-23-6"
datasheet = "https://www.st.com/resource/en/datasheet/usblc6-2.pdf"
keywords = ["usb", "ethernet", "video"]
footprint = "SOT-23-6"
footprint_filters = ["SOT?23*"]
pin_names = "hidden"

[[graphics]]
kind = "circle"
center = [-1.524, 0.0]
radius = 0.0001
width = 0.508

[[graphics]]
kind = "circle"
center = [-0.508, -2.032]
radius = 0.0001
width = 0.508

[[graphics]]
kind = "circle"
center = [-0.508, 4.572]
radius = 0.0001
width = 0.508

[[graphics]]
kind = "circle"
center = [0.508, -2.032]
radius = 0.0001
width = 0.508

[[graphics]]
kind = "circle"
center = [0.508, 4.572]
radius = 0.0001
width = 0.508

[[graphics]]
kind = "circle"
center = [1.524, 2.54]
radius = 0.0001
width = 0.508

[[graphics]]
kind = "polyline"
points = [[-2.54, 0.0], [2.54, 0.0]]

[[graphics]]
kind = "polyline"
points = [[-2.54, 2.54], [2.54, 2.54]]

[[graphics]]
kind = "polygon"
points = [[-2.032, -0.508], [-1.016, -0.508], [-1.524, -1.524]]

[[graphics]]
kind = "polyline"
points = [[-2.032, 3.048], [-1.016, 3.048]]

[[graphics]]
kind = "polyline"
points = [[-1.016, -1.524], [-2.032, -1.524]]

[[graphics]]
kind = "polygon"
points = [[-1.016, 4.064], [-2.032, 4.064], [-1.524, 3.048]]

[[graphics]]
kind = "polyline"
points = [[-0.508, 1.143], [-0.508, 0.762], [0.508, 0.762]]

[[graphics]]
kind = "polyline"
points = [[0.0, -2.54], [-0.508, -2.032], [0.508, -2.032], [0.0, -1.524], [0.0, 4.064], [-0.508, 4.572], [0.508, 4.572], [0.0, 5.08]]

[[graphics]]
kind = "polygon"
points = [[0.508, 1.778], [-0.508, 1.778], [0.0, 0.762]]

[[graphics]]
kind = "polyline"
points = [[1.016, -1.524], [2.032, -1.524]]

[[graphics]]
kind = "polyline"
points = [[1.016, 3.048], [2.032, 3.048]]

[[graphics]]
kind = "polygon"
points = [[2.032, -0.508], [1.016, -0.508], [1.524, -1.524]]

[[graphics]]
kind = "polygon"
points = [[2.032, 4.064], [1.016, 4.064], [1.524, 3.048]]

[[graphics]]
kind = "rect"
unit = 1
start = [-2.54, -2.794]
end = [2.54, 5.334]
width = 0.254
fill = "background"

[[graphics]]
kind = "polyline"
unit = 1
points = [[-0.508, -2.032], [-1.524, -2.032], [-1.524, 4.572], [-0.508, 4.572]]

[[graphics]]
kind = "polyline"
unit = 1
points = [[0.508, 4.572], [1.524, 4.572], [1.524, -2.032], [0.508, -2.032]]

[[pins]]
number = "1"
name = "I/O1"
type = "passive"
at = [-5.08, 0.0]
side = "left"
length = 2.54
unit = 1

[[pins]]
number = "3"
name = "I/O2"
type = "passive"
at = [-5.08, 2.54]
side = "left"
length = 2.54
unit = 1

[[pins]]
number = "5"
name = "VBUS"
type = "passive"
at = [0.0, -5.08]
side = "top"
length = 2.54
unit = 1

[[pins]]
number = "2"
name = "GND"
type = "passive"
at = [0.0, 7.62]
side = "bottom"
length = 2.54
unit = 1

[[pins]]
number = "6"
name = "I/O1"
type = "passive"
at = [5.08, 0.0]
side = "right"
length = 2.54
unit = 1

[[pins]]
number = "4"
name = "I/O2"
type = "passive"
at = [5.08, 2.54]
side = "right"
length = 2.54
unit = 1
