# imported from KiCad Connector_Generic:Conn_01x04
name = "Conn_01x04"
reference = "J"
description = "Generic connector, single row, 01x04, script generated (kicad-library-utils/schlib/autogen/connector/)"
keywords = ["connector"]
footprint = "JST_XH_B4B-XH-A_1x04_P2.50mm_Vertical"
footprint_filters = ["Connector*:*_1x??_*"]
pin_names = "hidden"
pin_name_offset = 1.016

[[graphics]]
kind = "rect"
unit = 1
start = [-1.27, -3.81]
end = [1.27, 6.35]
width = 0.254
fill = "background"

[[graphics]]
kind = "rect"
unit = 1
start = [-1.27, -2.667]
end = [0.0, -2.413]
width = 0.1524

[[graphics]]
kind = "rect"
unit = 1
start = [-1.27, -0.127]
end = [0.0, 0.127]
width = 0.1524

[[graphics]]
kind = "rect"
unit = 1
start = [-1.27, 2.413]
end = [0.0, 2.667]
width = 0.1524

[[graphics]]
kind = "rect"
unit = 1
start = [-1.27, 4.953]
end = [0.0, 5.207]
width = 0.1524

[[pins]]
number = "1"
name = "Pin_1"
type = "passive"
at = [-5.08, -2.54]
side = "left"
length = 3.81
unit = 1

[[pins]]
number = "2"
name = "Pin_2"
type = "passive"
at = [-5.08, 0.0]
side = "left"
length = 3.81
unit = 1

[[pins]]
number = "3"
name = "Pin_3"
type = "passive"
at = [-5.08, 2.54]
side = "left"
length = 3.81
unit = 1

[[pins]]
number = "4"
name = "Pin_4"
type = "passive"
at = [-5.08, 5.08]
side = "left"
length = 3.81
unit = 1
