# from KiCad Transistor_FET:DMT6008LFG, drain pad 7 added
name = "DMT10H015LFG"
reference = "Q"
description = "100V N-Channel MOSFET, 23.5mOhm at 4.5V, PowerDI-3333-8"
datasheet = "https://www.diodes.com/assets/Datasheets/DMT10H015LFG.pdf"
keywords = ["Power", "MOSFET", "N-MOS"]
footprint = "Diodes_PowerDI3333-8_UXC_3.3x3.3mm_P0.65mm"
footprint_filters = ["Diodes*PowerDI3333*"]
pin_names = "hidden"

[[graphics]]
kind = "polyline"
points = [[0.254, -1.905], [0.254, 1.905]]
width = 0.254

[[graphics]]
kind = "polyline"
points = [[0.254, 0.0], [-2.54, 0.0]]

[[graphics]]
kind = "polyline"
points = [[0.762, -2.286], [0.762, -1.27]]
width = 0.254

[[graphics]]
kind = "polyline"
points = [[0.762, -0.508], [0.762, 0.508]]
width = 0.254

[[graphics]]
kind = "polyline"
points = [[0.762, 1.27], [0.762, 2.286]]
width = 0.254

[[graphics]]
kind = "polyline"
points = [[0.762, 1.778], [3.302, 1.778], [3.302, -1.778], [0.762, -1.778]]

[[graphics]]
kind = "polygon"
points = [[1.016, 0.0], [2.032, -0.381], [2.032, 0.381]]
fill = "solid"

[[graphics]]
kind = "circle"
center = [1.651, 0.0]
radius = 2.794
width = 0.254

[[graphics]]
kind = "polyline"
points = [[2.54, -2.54], [2.54, -1.778]]

[[graphics]]
kind = "circle"
center = [2.54, -1.778]
radius = 0.254
fill = "solid"

[[graphics]]
kind = "circle"
center = [2.54, 1.778]
radius = 0.254
fill = "solid"

[[graphics]]
kind = "polyline"
points = [[2.54, 2.54], [2.54, 0.0], [0.762, 0.0]]

[[graphics]]
kind = "polyline"
points = [[2.794, -0.508], [2.921, -0.381], [3.683, -0.381], [3.81, -0.254]]

[[graphics]]
kind = "polygon"
points = [[3.302, -0.381], [2.921, 0.254], [3.683, 0.254]]

[[pins]]
number = "4"
name = "G"
type = "passive"
at = [-5.08, 0.0]
side = "left"
length = 2.54
unit = 1

[[pins]]
number = "5"
name = "D"
type = "passive"
at = [2.54, -5.08]
side = "top"
length = 2.54
unit = 1

[[pins]]
number = "1"
name = "S"
type = "passive"
at = [2.54, 5.08]
side = "bottom"
length = 2.54
unit = 1

[[pins]]
number = "2"
name = "S"
type = "passive"
at = [2.54, 5.08]
side = "bottom"
length = 2.54
unit = 1
hidden = true

[[pins]]
number = "3"
name = "S"
type = "passive"
at = [2.54, 5.08]
side = "bottom"
length = 2.54
unit = 1
hidden = true

[[pins]]
number = "7"
name = "D"
type = "passive"
at = [2.54, -5.08]
side = "top"
length = 2.54
unit = 1
hidden = true
