# imported from KiCad Jumper:SolderJumper_2_Open
name = "SolderJumper_2_Open"
reference = "JP"
description = "Solder Jumper, 2-pole, open"
keywords = ["solder", "jumper", "SPST"]
footprint = "SolderJumper-2_P1.3mm_Open_RoundedPad1.0x1.5mm"
footprint_filters = ["SolderJumper*Open*"]
pin_names = "hidden"
hide_pin_numbers = true

[[graphics]]
kind = "polyline"
points = [[-0.254, -1.016], [-0.254, 1.016]]

[[graphics]]
kind = "arc"
start = [-0.254, 1.016]
mid = [-1.2656, 0.0]
end = [-0.254, -1.016]

[[graphics]]
kind = "arc"
start = [-0.254, 1.016]
mid = [-1.2656, 0.0]
end = [-0.254, -1.016]
fill = "solid"

[[graphics]]
kind = "arc"
start = [0.254, -1.016]
mid = [1.2656, 0.0]
end = [0.254, 1.016]

[[graphics]]
kind = "arc"
start = [0.254, -1.016]
mid = [1.2656, 0.0]
end = [0.254, 1.016]
fill = "solid"

[[graphics]]
kind = "polyline"
points = [[0.254, -1.016], [0.254, 1.016]]

[[pins]]
number = "1"
name = "A"
type = "passive"
at = [-3.81, 0.0]
side = "left"
length = 2.54
unit = 1

[[pins]]
number = "2"
name = "B"
type = "passive"
at = [3.81, 0.0]
side = "right"
length = 2.54
unit = 1
