# imported from KiCad Diode_SMD:D_SOD-123F
name = "D_SOD-123F"
description = "D_SOD-123F"
tags = ["D_SOD-123F"]
mount = "smd"
model = "${KICAD9_3DMODEL_DIR}/Diode_SMD.3dshapes/D_SOD-123F.step"

[[pads]]
number = "1"
kind = "smd"
shape = "roundrect"
at = [-1.4, 0.0]
size = [1.1, 1.1]
roundrect_ratio = 0.2272727273
layers = ["F.Cu", "F.Mask", "F.Paste"]

[[pads]]
number = "2"
kind = "smd"
shape = "roundrect"
at = [1.4, 0.0]
size = [1.1, 1.1]
roundrect_ratio = 0.2272727273
layers = ["F.Cu", "F.Mask", "F.Paste"]

[[graphics]]
kind = "text"
layer = "F.SilkS"
at = [-0.127, -1.905]
text = "${REFERENCE}"
size = 1.0

[[graphics]]
kind = "text"
layer = "F.Fab"
at = [0.0, 2.1]
text = "${VALUE}"
size = 1.0

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-2.21, -1.0]
end = [-2.21, 1.0]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-2.21, -1.0]
end = [1.65, -1.0]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-2.21, 1.0]
end = [1.65, 1.0]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [-2.2, -1.15]
end = [-2.2, 1.15]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [-2.2, -1.15]
end = [2.2, -1.15]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [2.2, -1.15]
end = [2.2, 1.15]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [2.2, 1.15]
end = [-2.2, 1.15]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-1.4, -0.9]
end = [1.4, -0.9]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-1.4, 0.9]
end = [-1.4, -0.9]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.75, 0.0]
end = [-0.35, 0.0]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.35, 0.0]
end = [-0.35, -0.55]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.35, 0.0]
end = [-0.35, 0.55]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.35, 0.0]
end = [0.25, -0.4]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [0.25, -0.4]
end = [0.25, 0.4]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [0.25, 0.0]
end = [0.75, 0.0]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [0.25, 0.4]
end = [-0.35, 0.0]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [1.4, -0.9]
end = [1.4, 0.9]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [1.4, 0.9]
end = [-1.4, 0.9]
width = 0.1

[[graphics]]
kind = "text"
layer = "F.Fab"
at = [-0.127, -1.905]
text = "${REFERENCE}"
size = 1.0
