# imported from KiCad Package_SON:Diodes_PowerDI3333-8_UXC_3.3x3.3mm_P0.65mm
name = "Diodes_PowerDI3333-8_UXC_3.3x3.3mm_P0.65mm"
description = "Diodes Incorporated PowerDI3333-8 UXC, 3.05x3.05x0.8mm Body, https://www.diodes.com/assets/Package-Files/PowerDI3333-8%20(Type%20UXC).pdf"
tags = ["PowerDI", "0.65"]
mount = "smd"
model = "${KICAD9_3DMODEL_DIR}/Package_SON.3dshapes/Diodes_PowerDI3333-8.step"

[[pads]]
kind = "smd"
shape = "roundrect"
at = [-0.22, -0.73]
size = [0.6, 1.0]
roundrect_ratio = 0.25
layers = ["F.Paste"]

[[pads]]
kind = "smd"
shape = "roundrect"
at = [-0.22, 0.71]
size = [0.6, 1.0]
roundrect_ratio = 0.25
layers = ["F.Paste"]

[[pads]]
kind = "smd"
shape = "roundrect"
at = [0.6, -0.73]
size = [0.6, 1.0]
roundrect_ratio = 0.25
layers = ["F.Paste"]

[[pads]]
kind = "smd"
shape = "roundrect"
at = [0.6, 0.71]
size = [0.6, 1.0]
roundrect_ratio = 0.25
layers = ["F.Paste"]

[[pads]]
kind = "smd"
shape = "roundrect"
at = [1.45, -0.98]
size = [0.7, 0.4]
roundrect_ratio = 0.25
layers = ["F.Paste"]

[[pads]]
kind = "smd"
shape = "roundrect"
at = [1.45, -0.32]
size = [0.7, 0.4]
roundrect_ratio = 0.25
layers = ["F.Paste"]

[[pads]]
kind = "smd"
shape = "roundrect"
at = [1.45, 0.32]
size = [0.7, 0.4]
roundrect_ratio = 0.25
layers = ["F.Paste"]

[[pads]]
kind = "smd"
shape = "roundrect"
at = [1.45, 0.98]
size = [0.7, 0.4]
roundrect_ratio = 0.25
layers = ["F.Paste"]

[[pads]]
number = "1"
kind = "smd"
shape = "roundrect"
at = [-1.5, -0.975]
size = [0.42, 0.6]
rotation = 270.0
roundrect_ratio = 0.25
layers = ["F.Cu", "F.Mask", "F.Paste"]
count = 4
pitch = [0.0, 0.65]

[[pads]]
number = "5"
kind = "smd"
shape = "custom"
at = [0.35, 0.715]
size = [1.0, 1.0]
rotation = 270.0
layers = ["F.Cu", "F.Mask"]
points = [[-0.6, 0.95], [-0.6, -1.45], [-0.18, -1.45], [-0.18, -0.95], [0.05, -0.95], [0.05, -1.45], [0.47, -1.45], [0.47, -0.95], [0.6, -0.95], [0.6, 0.95]]

[[pads]]
number = "7"
kind = "smd"
shape = "custom"
at = [0.35, -0.715]
size = [1.0, 1.0]
rotation = 270.0
layers = ["F.Cu", "F.Mask"]
points = [[-0.6, 0.95], [-0.6, -0.95], [-0.47, -0.95], [-0.47, -1.45], [-0.05, -1.45], [-0.05, -0.95], [0.18, -0.95], [0.18, -1.45], [0.6, -1.45], [0.6, 0.95]]

[[graphics]]
kind = "text"
layer = "F.SilkS"
at = [0.0, -2.4]
text = "${REFERENCE}"
size = 1.0

[[graphics]]
kind = "text"
layer = "F.Fab"
at = [0.0, 3.4]
text = "${VALUE}"
size = 1.0

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-1.625, 1.625]
end = [-1.625, 1.45]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-1.625, 1.625]
end = [1.625, 1.625]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-1.37, -1.625]
end = [1.625, -1.625]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [1.625, -1.45]
end = [1.625, -1.625]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [1.625, 1.45]
end = [1.625, 1.625]
width = 0.15

[[graphics]]
kind = "polygon"
layer = "F.SilkS"
points = [[-1.64, -1.445], [-2.12, -1.445], [-1.64, -1.925], [-1.64, -1.445]]
width = 0.15
fill = "solid"

[[graphics]]
kind = "rect"
layer = "F.CrtYd"
start = [-2.05, -1.78]
end = [2.05, 1.78]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-1.525, -0.925]
end = [-1.525, 1.525]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-1.525, 1.525]
end = [1.525, 1.525]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.925, -1.525]
end = [-1.525, -0.925]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.925, -1.525]
end = [1.525, -1.525]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [1.525, -1.525]
end = [1.525, 1.525]
width = 0.1

[[graphics]]
kind = "text"
layer = "F.Fab"
at = [0.0, 0.0]
text = "${REFERENCE}"
size = 0.8
rotation = 180.0
