# imported from KiCad Package_SON:VSON-10-1EP_3x3mm_P0.5mm_EP1.65x2.4mm
name = "VSON-10-1EP_3x3mm_P0.5mm_EP1.65x2.4mm"
description = "VSON 10 Thermal on 11 3x3mm Pitch 0.5mm http://chip.tomsk.ru/chip/chipdoc.nsf/Package/D8A64DD165C2AAD9472579400024FC41!OpenDocument"
tags = ["VSON", "10", "Thermal", "on", "11", "3x3mm", "Pitch", "0.5mm"]
mount = "smd"
model = "${KICAD9_3DMODEL_DIR}/Package_SON.3dshapes/VSON-10-1EP_3x3mm_P0.5mm_EP1.65x2.4mm.step"

[[pads]]
kind = "smd"
shape = "rect"
at = [-0.4125, -0.8]
size = [0.64, 0.64]
layers = ["F.Paste"]

[[pads]]
kind = "smd"
shape = "rect"
at = [-0.4125, 0.0]
size = [0.64, 0.64]
layers = ["F.Paste"]

[[pads]]
kind = "smd"
shape = "rect"
at = [-0.4125, 0.8]
size = [0.64, 0.64]
layers = ["F.Paste"]

[[pads]]
kind = "smd"
shape = "rect"
at = [0.4125, -0.8]
size = [0.64, 0.64]
layers = ["F.Paste"]

[[pads]]
kind = "smd"
shape = "rect"
at = [0.4125, 0.0]
size = [0.64, 0.64]
layers = ["F.Paste"]

[[pads]]
kind = "smd"
shape = "rect"
at = [0.4125, 0.8]
size = [0.64, 0.64]
layers = ["F.Paste"]

[[pads]]
number = "1"
kind = "smd"
shape = "roundrect"
at = [-1.475, -1.0]
size = [0.85, 0.28]
roundrect_ratio = 0.25
layers = ["F.Cu", "F.Mask", "F.Paste"]
count = 5
pitch = [0.0, 0.5]

[[pads]]
number = "6"
kind = "smd"
shape = "roundrect"
at = [1.475, 1.0]
size = [0.85, 0.28]
roundrect_ratio = 0.25
layers = ["F.Cu", "F.Mask", "F.Paste"]
count = 5
pitch = [0.0, -0.5]

[[pads]]
number = "11"
kind = "smd"
shape = "rect"
at = [-0.25, -1.55]
size = [0.28, 0.7]
layers = ["F.Cu", "F.Mask", "F.Paste"]

[[pads]]
number = "11"
kind = "smd"
shape = "rect"
at = [-0.25, 1.55]
size = [0.28, 0.7]
layers = ["F.Cu", "F.Mask", "F.Paste"]

[[pads]]
number = "11"
kind = "smd"
shape = "rect"
at = [0.0, 0.0]
size = [1.65, 2.4]
layers = ["F.Cu", "F.Mask"]

[[pads]]
number = "11"
kind = "smd"
shape = "rect"
at = [0.25, -1.55]
size = [0.28, 0.7]
layers = ["F.Cu", "F.Mask", "F.Paste"]

[[pads]]
number = "11"
kind = "smd"
shape = "rect"
at = [0.25, 1.55]
size = [0.28, 0.7]
layers = ["F.Cu", "F.Mask", "F.Paste"]

[[graphics]]
kind = "text"
layer = "F.SilkS"
at = [0.0, -2.9]
text = "${REFERENCE}"
size = 1.0

[[graphics]]
kind = "text"
layer = "F.Fab"
at = [0.0, 3.0]
text = "${VALUE}"
size = 1.0

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-1.6, 1.5]
end = [-1.6, 1.6]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-1.6, 1.6]
end = [-0.8, 1.6]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-0.8, -1.6]
end = [-1.26, -1.6]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [0.8, -1.6]
end = [1.6, -1.6]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [0.8, 1.6]
end = [1.6, 1.6]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [1.6, -1.6]
end = [1.6, -1.5]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [1.6, 1.6]
end = [1.6, 1.5]
width = 0.15

[[graphics]]
kind = "polygon"
layer = "F.SilkS"
points = [[-1.6, -1.48], [-2.08, -1.48], [-1.6, -1.96], [-1.6, -1.48]]
width = 0.15
fill = "solid"

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [-2.15, -2.15]
end = [2.15, -2.15]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [-2.15, 2.15]
end = [-2.15, -2.15]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [2.15, -2.15]
end = [2.15, 2.15]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [2.15, 2.15]
end = [-2.15, 2.15]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-1.5, -0.5]
end = [-1.5, 1.5]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-1.5, -0.5]
end = [-0.5, -1.5]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-1.5, 1.5]
end = [1.5, 1.5]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.5, -1.5]
end = [1.5, -1.5]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [1.5, -1.5]
end = [1.5, 1.5]
width = 0.1

[[graphics]]
kind = "text"
layer = "F.Fab"
at = [0.0, 0.0]
text = "${REFERENCE}"
size = 0.8
